Extra translations between LogDensityFunctions and models (#1267)
Closes #1232

This PR 'closes the loop' between LogDensityFunctions and models, in
other words, it makes sure that anything you want to do with a model can
be done with an LDF, and vice versa.

It does so by providing safe conversions between vectorised parameters,
initialisation strategies, and accumulators.

Specifically, it allows you to:

- **Given a vector of parameters and an LDF, generate an initialisation
strategy that lets you run a model.** (i.e., the equivalent of
`unflatten(vi, x); evaluate!!(model, vi)` but without using a VarInfo)

This was technically already in the codebase (it used to be called
`InitFromParams{<:VectorWithRanges}`, and LDF used it internally -- this
is exactly what FastLDF uses 😉). This PR just cleans up the constructors
and exports it as `InitFromVector(vector, ldf)` so that other people can
also use it.

- **Given an initialisation strategy and an LDF, generate a set of
vectorised parameters** (i.e., the equivalent of `vi = VarInfo(model),
vi[:]` but again without using a VarInfo)

Apart from removing the need for a VarInfo, the new functions also do so
in a way that ensures correctness (as far as possible). The old approach
was riddled with potential correctness issues and as a user you had to
be very much on top of things to make sure that you didn't screw
something up.*

See docs for more info:
https://turinglang.org/DynamicPPL.jl/previews/PR1267/ldf/models/

----------

\* Example:

```julia
julia> using DynamicPPL, Distributions, LogDensityProblems

julia> @model f() = x ~ Beta(2, 2); model = f(); ldf = LogDensityFunction(f()); # Unlinked!

julia> LogDensityProblems.logdensity(ldf, [0.5]), logpdf(Beta(2, 2), 0.5)
(0.4054651081081644, 0.4054651081081644)

julia> # Different model, different variable name, different link status...
       @model g() = y ~ Beta(2, 2); vi = link!!(VarInfo(g()), g());
g (generic function with 2 methods)

julia> # But by calling vi[:] we lose all that information...
       ps = vi[:]
1-element Vector{Float64}:
 1.7940959094517983

julia> # This is completely meaningless!
        LogDensityProblems.logdensity(ldf, ps)
-Inf
```

With the current approach, it will tell you you're doing something
silly:

```julia
julia> oavi = OnlyAccsVarInfo(VectorValueAccumulator());

julia> vvals = get_vector_values(last(init!!(g(), oavi, InitFromPrior(), LinkAll())))
VarNamedTuple
└─ y => LinkedVectorValue{Vector{Float64}, ComposedFunction{DynamicPPL.UnwrapSingletonTransform{Tuple{}}, ComposedFunction{Bijectors.Inverse{Bijectors.Logit{Float64, Float64}}, DynamicPPL.ReshapeTransform{Tuple{Int64}, Tuple{}}}}, Tuple{}}([1.7044738291818293], DynamicPPL.UnwrapSingletonTransform{Tuple{}}(()) ∘ (Bijectors.Inverse{Bijectors.Logit{Float64, Float64}}(Bijectors.Logit{Float64, Float64}(0.0, 1.0)) ∘ DynamicPPL.ReshapeTransform{Tuple{Int64}, Tuple{}}((1,), ())), ())

julia> to_vector_input(vvals, ldf)
ERROR: type NamedTuple has no field y
[...]
```

---------

Co-authored-by: Xianda Sun <5433119+sunxd3@users.noreply.github.com>