Make `rand(model)` return a VNT (#1233)
Closes #1200

Previously, `rand(model)` would attempt to return a NamedTuple. This was
fine for very simple models but would give suboptimal results for
VarNames that had non-identity optics:

```julia
julia> using DynamicPPL, Distributions

julia> @model function f()
          x = zeros(2)
          x[1] ~ Normal()
          x[2] ~ Normal()
       end
f (generic function with 2 methods)

julia> rand(f())
(var"x[1]" = -0.5828803286949055, var"x[2]" = -0.3835353813031822)
```

This PR changes it so that `rand(model)` returns a VNT:

```julia
julia> rand(f())
VarNamedTuple
└─ x => PartialArray size=(2,) data::Vector{Float64}
        ├─ (1,) => 1.4082006737234858
        └─ (2,) => -0.16826810802235967
```

which means that you can do things like

```julia
julia> rand(f())[@varname(x)]
2-element Vector{Float64}:
 2.029272896483767
 2.7286168689432753
```

correctly.

## Conversion

This PR also introduces a (type-stable) conversion function from VNT to
NamedTuple in the case where all VarNames are identity optics. So the
model above will fail:

```julia
julia> NamedTuple(rand(f()))
ERROR: ArgumentError: Cannot convert VarNamedTuple containing non-identity VarNames to NamedTuple. To create a NamedTuple, all keys in the VarNamedTuple must be top-level symbols.
[...]
```

but a model where there are only identity optics will be fine:

```julia
julia> @model function g()
           x ~ Normal()
           y ~ product_distribution(fill(Normal(), 3))
       end
g (generic function with 2 methods)

julia> NamedTuple(rand(g()))
(x = -0.06007341411360624, y = [1.2523261361295535, 0.4303782358657348, 0.3958208396742736])
```

Conversion to Dict already works, using `Dict{K,V}(pairs(vnt))`, which
is standard Julia syntax for converting things to Dicts, and so I don't
consider it necessary to implement something separately for this.

## API

Since we have gotten rid of some of the functionality we don't need,
this was also a good time to clean up the API.

This PR removes

- `values_as(vi, NamedTuple)` -- no longer needed (should use VAIMAcc
and convert the VNT to NamedTuple)
- `values_as(vi, AbstractDict)` -- no longer needed (technically to be
fully correct, one should use VAIMAcc and convert the VNT to Dict; but
in practice you can also use `Dict{K,V}(pairs(vi))`)
- `values_as(vi, Vector)` -- replaced with
`internal_values_as_vector(vi)` which has a much better name

Note that VAIMAcc is more accurate since that ensures that the link
transforms used are not out of date (whereas `pairs(vi)`, and the old
`values_as`, would potentially be inaccurate if the values were changed
without re-evaluating the model).